### ISSUE TITLE
"This document has move. Moved Permanently"

### ISSUE THREAD

**Issue by datawizard1337** [datawizard1337/ARGUS#23]
Sometimes HTML 300 errors do not seem to be catched (or not sent in the first place) when parsing subpages. This appears quite often when "http" subpages redirect to their "https" counterparts. 
Text extract is then:
"This document has move. Moved Permanently"

**Comment by cordoba27** [comment]
The following code snippet for the textspider is a possible solution:

`  #skip broken urls
if response.status == 301: # Moved Permanently
return self.processURLstack(response)

if response.status == 302: # Found
return self.processURLstack(response)`

**Comment by datawizard1337** [comment]
That fixed it!
