### ISSUE TITLE
Post-processing multiple chunks

### ISSUE THREAD

**Issue by cordoba27** [datawizard1337/ARGUS#32]
A Key Error is raised when there are multiple outputs in the chunks. 

in postprocessing.py, line 48:
```
print("Processed {} of files".format(report_ticks[ticks]))
KeyError: 5
```

**Comment by datawizard1337** [comment]
If the error is not so easy to fix, we can still delete that part of the code.

**Comment by cordoba27** [comment]
Error was fixed by restructuring the affected part of the code.
