### ISSUE TITLE
Tkinter: [WinError2] System cant find the specified file

### ISSUE THREAD

**Issue by lalo3392** [datawizard1337/ARGUS#39]
Hi I'm really new to Argus.
Once the scraping ends I get an exception in Tinter callback and can't save the results. I ttach a screenshot of the issue.
Thanks

![Error Argus](https://user-images.githubusercontent.com/61836615/76309977-32020680-62ce-11ea-9d26-ba968dc616e7.PNG)

**Comment by datawizard1337** [comment]
Hey lalo, 
Are you sure that you have taken into account this warning:

Warning: Please make sure that ARGUS and your URL file are not located in directories with paths containing ".", e.g. "C:\my.folder\data.txt"!

**Comment by lalo3392** [comment]
Hey, thanks for your reply

I double checked and there are no "." in the paths. 
A collague of mine suggested another cause: " There can be an issue with Windows because it does not conform to POSIX by default.

I'm really a begginer and I'm not sure what this is, bu I hope its useful.

**Comment by datawizard1337** [comment]
When exactly does this error occure? Immediately after you clicked "start scraping"?

Please also check whether you are able to run "scrapyd" manually. Start your command line (e.g. by pressing windows button and R and then enter "cmd") and then enter "scrapyd".

**Comment by lalo3392** [comment]
It's immediately after I press "Postprocessing". I found the cvs output files in the argus directory, so the scrapping is working. But just postprocessing is not.

**Comment by datawizard1337** [comment]
Could you please send a complete screenshot of the error message?

**Comment by cordoba27** [comment]
Does the error still occur for you? If so, I hope that it'll disappear with the next update, as we are working on restructuring the postprocessing function of ARGUS.

**Comment by FrancoMMV** [comment]
Hello everyone! Just started with ARGUS and I am experiencing this same problem. Just followed the instructions to get the ARGUS running. Here is the screenshot:
![Screenshot 2023-12-05 184411](https://github.com/datawizard1337/ARGUS/assets/56807958/807b189c-9c6b-4a90-b298-714faa164dd6)

**Comment by datawizard1337** [comment]
@cordoba27 do you remember the fix for this?

**Comment by FrancoMMV** [comment]
Hi, I checked all installations again and added ...Anaconda3\Script to the path and the code line subprocess.run(r"TSKILL scrapyd", shell=True) and it worked. However, it was searching for a \chunks\chunks folder instead of just chunks creating a new error easily solved by creating the path it was looking for.
