### ISSUE TITLE
Getting started with ARGUS

### ISSUE THREAD

**Issue by DioLimpens** [datawizard1337/ARGUS#53]
Dear all, 

As I am a novice in webcrawling and not experience in python, I request your help. I might want to make use of ARGUS for my Master thesis, but do not get it working. I have followed all steps in the readme and reinstalled everything even. Yet, when starting the crawler through by either launching the no_GUI or the ARGUS.py file in the command prompt (as the GUI won't start for me) and testrun on the url list in the  misc folder, it seems that the spider starts but never ends (I am not certain on this) and never shows up in the scrapyd web interface, as none appear under pending, running, or finished. 

So far: I've checked: 
- all packages multiple times,
-  if cURL was added to PATH (as it can be commanded in the prompt), 
- tried with pre-launching Scrapyd, 
- if the directories the files were stored.

I hope you are able to help me further as I am much interested in learning more about webmining, and programming in general. 
If you require more information or the output I receive, please let me know. 

Kind regards, 

Dio

**Comment by datawizard1337** [comment]
Hey Dio, would you be so nice and post a screenshot of your command line interface after launching the scraping?

**Comment by DioLimpens** [comment]
Dear Jan, Thanks for the quick reply. 
Hereby the screenshots attached, I preloaded scrapyd before launching ARGUS_noGUI with the example url-list in misc. 
Hopefully allows this to get an insight on where I am making mistakes.
I seems to me that it has an error on the command -list-, yet this would be standard recognized by python and works fine in the shell. 
Thank you in advance for your aid.

![ARGUS_noGUI run](https://user-images.githubusercontent.com/94067244/149199835-6ff54ebf-8dfa-40af-88ee-d96c169c157d.PNG)
![Scrapyd server output](https://user-images.githubusercontent.com/94067244/149199846-3e5b07ba-ccfc-47e7-8599-845fdf8858cf.PNG)
![Scrapyd website output](https://user-images.githubusercontent.com/94067244/149199857-008769c1-9159-416c-9ddd-199e2f9890b2.PNG)

**Comment by datawizard1337** [comment]
Have you tried to start the scrapyd server from inside the ARGUS directory? 
Navigate to the directory and then launch your cmd by, for example, clicking the path in the navigation bar, enter "cmd" and enter.
![image](https://user-images.githubusercontent.com/39303881/149208749-d2952501-019b-4483-925c-8ef28797faa8.png)

**Comment by davidlenz** [comment]
Some further reading on this:

- https://github.com/scrapy/scrapyd/issues/352
- https://stackoverflow.com/questions/38052549/scrapy-1-1-0-no-active-project

**Comment by DioLimpens** [comment]
Thanks both!
Indeed with running scrapyd from the ARGUS directory resolved the first issue, after adding the anaconda paths to the system path. I was running everything from the Anaconda cmd prompt.
For my understanding and learning: this has to do with the configuration and settings files for scrapy in this directory?

Furthermore, did the post-processing result in an error (Exception in Tkinter callback) similar to the issue "ebergam" had in February. His addition `subprocess.run(r"TSKILL scrapyd", shell=True)` solved this problem as well for me.

**Comment by datawizard1337** [comment]
Yes, if you are running scrapyd outside of the ARGUS directory, scrapy won't find the project files.
Happy that we could help you.
