### ISSUE TITLE
Only scrape urls

### ISSUE THREAD

**Issue by DioLimpens** [datawizard1337/ARGUS#54]
Hi, 

As I am fairly new to programming, I have no idea where to start with making changes. 
I intent to solely scrape the webpages for urls, mainly urls/hyperlinks to other websites than the host. Where should I start looking at? 
Your help would be very welcome.

**Comment by datawizard1337** [comment]
Dear Dio,
I am sorry to tell you that this would indeed require profound changes to the program that require advanced python knowledge.
Best
Jan
